name: something-fun-123
owner: randomduck
package: '.'
capabilities:
  database:
    engine: mysql
volumes:
- name: wp-content
  mount: /app/wp-content
scaling:
  mode: single_concurrency
jobs:
- name: wp-cron
  trigger: '*/15 * * * *'
  action:
    fetch:
      path: /wp-cron.php
      timeout: '10m'
kind: wasmer.io/App.v0
