[package]
entrypoint = "run"

[dependencies]
"php/php" = "=8.3.403"
"amin/bash" = "*"

[fs]
"/app" = "."

[[command]]
name = "run"
module = "php/php:php"
runner = "wasi"
[command.annotations.wasi]
main-args = [
    "-t",
    "/app",
    "-S",
    "localhost:8080",
    "-d",
    "memory_limit=256M",
    "-d",
    "max_execution_time=600",
    "-d",
    "max_input_time=600",
    "-d",
    "max_input_vars=4096",
    "-d",
    "upload_max_filesize=1024M",
    "-d",
    "post_max_size=1024M",
]

[[command]]
name = "install"
module = "php/php:php"
runner = "wasi"
[command.annotations.wasi]
main-args = ["-d", "opcache.enable=0", "-f", "/app/wasmer/install.php"]

[[command]]
name = "install-language"
module = "php/php:php"
runner = "wasi"
