[package]
entrypoint = "run"

[dependencies]
"php/php-eh" = "=8.3.404-beta.8"
"wasmer/bash" = "=1.0.21"
"wasmer/static-web-server" = "*"
"curl/curl" = "*"

[fs]
"/app" = "."

[[command]]
name = "serve-static"
module = "wasmer/static-web-server:webserver"
runner = "wasi"
[command.annotations.wasi]
main-args = ["--root", "/app"]


[[command]]
name = "run"
module = "php/php-eh:php"
runner = "wasi"
[command.annotations.wasi]
main-args = [
  "-t",
  "/app",
  "-S",
  "localhost:8080",
  "-d",
  "memory_limit=512M",
  "-d",
  "max_execution_time=2400",
  "-d",
  "max_input_time=2400",
  "-d",
  "max_input_vars=16384",
  "-d",
  "upload_max_filesize=16384M",
  "-d",
  "post_max_size=16384M",
]

[[command]]
name = "install-wp"
module = "wasmer/bash:bash"
runner = "wasi"
[command.annotations.wasi]
main-args = ["/app/install/install.sh"]

[[command]]
name = "wp-cron"
module = "php/php-eh:php"
runner = "wasi"
[command.annotations.wasi]
main-args = [
  "/app/wp-cli.phar",
  "cron",
  "event",
  "run",
  "--due-now",
  "--allow-root",
  "--path=/app",
]
